export const lightTheme = {
    headerBody: '#f5f5f5',
    body: '#FFF',
    text: '#363537',
    toggleBorder: '#FFF',
    background: '#363537',
    border: '#1c1c1c',
    borderHover: '#ffdf66',
    headerTitle: '#1c1c1c',
    heroTitle: '#f5f5f5',
    featureShadow: '#1c1c1c',
    alternateBackground: '#f1f1f1',
    cardBackground: '#e0e0e0',
    registerBox: '#f5f5f5',    
    link: 'coral',
    linkActive: '#ff007d',
    headerBackground: '#d0d0d0',
    verifyCodeBackground: '#d0d0d0'
}

export const darkTheme = {
    headerBody: '#252426',
    body: '#363537',
    text: '#FAFAFA',
    toggleBorder: '#6B8096',
    background: '#999',    
    border: '#f5f5f5',    
    borderHover: '#ffdf66',
    headerTitle: '#f5f5f5',
    heroTitle: '#f5f5f5',    
    featureShadow: '#f5f5f5',
    alternateBackground: '#242325',
    cardBackground: '#1c1c1c',
    registerBox: '#4f4f4f',
    link: 'coral',    
    linkActive: '#ffffff',
    headerBackground: '#0b0b0b',
    verifyCodeBackground: '#0b0b0b',
}